FROM node:16 as build
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build 

FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html

