###
GET http://localhost:5000/api/response/getResponseByCompany/8b874ad2-073c-476d-89f6-f14799d10474/62d2fa933a83672d944b437a?year=2023
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDJmYTkzM2E4MzY3MmQ5NDRiNDM3YSIsIm5hbWUiOiJQTE0tTVMgQWRtaW4iLCJlbWFpbCI6InBsbW1zQHRlY2huaWEuY29tIiwiYWRtaW4iOnRydWUsIm9yZ2FuaXphdGlvbiI6IlRFQ0hOSUEiLCJjcmVhdGVkRm9ybXMiOlsiOGI4NzRhZDItMDczYy00NzZkLTg5ZjYtZjE0Nzk5ZDEwNDc0IiwiMDc1NTA3ODctMzkwNi00OWMxLTk1Y2UtNTM5NGRmM2NhMmI2Il0sImlhdCI6MTY3OTkyOTUwNn0.mkBHNz74Mujb150dp5ttKB23o2zOPjjUpJENBeEKeEY
